### PR TITLE
Fixed if/else clauses

### LINKED ISSUE #44: Does not compile due to if.. else identation errors
Here's the error log:

```sh
~/Sawteeth> cmake .
~/Sawteeth> make | nc termbin.com 9999
/boot/home/Sawteeth/Source/stAiffWindow.cpp: In member function 'void stAiffWindow::Thread()':
/boot/home/Sawteeth/Source/stAiffWindow.cpp:116:4: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
    if (sbuf[c] > max) max = sbuf[c];if (sbuf[c] < min) min = sbuf[c];
    ^~
/boot/home/Sawteeth/Source/stAiffWindow.cpp:116:37: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
    if (sbuf[c] > max) max = sbuf[c];if (sbuf[c] < min) min = sbuf[c];
                                     ^~
cc1plus: all warnings being treated as errors
make[2]: *** [Source/CMakeFiles/Sawteeth.dir/stAiffWindow.cpp.o] Error 1
make[1]: *** [Source/CMakeFiles/Sawteeth.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by alwayslivid**
This resolves #44, which I opened. The codebase still does not abide by the code guidelines, but an initial commit that resolves the issues that prevent the program from being compiled is a good first start.

### CODE REVIEW

File: Source/stAiffWindow.cpp [hunk 1]
```diff
@@ -113,8 +113,15 @@ void stAiffWindow::Thread()
...
-			if (sbuf[c] > max) max = sbuf[c];if (sbuf[c] < min) min = sbuf[c];
-			if (sbuf[c] > 0.999) sbuf[c] = 0.999; else if (sbuf[c] < -0.999) sbuf[c] = -0.999;
+			if (sbuf[c] > max)
+				max = sbuf[c];
+
+			if (sbuf[c] < min)
+				min = sbuf[c];
+
+			if (sbuf[c] > 0.999)
+				sbuf[c] = 0.999; else if (sbuf[c] < -0.999) sbuf[c] = -0.999;
```
Comment (pulkomandy) [inline Source/stAiffWindow.cpp]: well you could fix the style of that else if as well while you're at it

File: Source/stApp.cpp [hunk 2]
```diff
@@ -117,9 +117,12 @@ void stApp::RefsReceived(BMessage *message)
 							"OK",0,0,B_WIDTH_AS_USUAL,B_STOP_ALERT);
 						alert->Go();
 					}
-				}else
+				}
+				else
```
Comment (pulkomandy) [inline Source/stApp.cpp]: the style compliant way is `} else {` all in one line

File: Source/stAiffWindow.cpp [hunk 3]
```diff
@@ -113,8 +113,15 @@ void stAiffWindow::Thread()
 		for (int c = 0 ; c< (2 * sbufs); c++){
 
 			//max, min and clipping
-			if (sbuf[c] > max) max = sbuf[c];if (sbuf[c] < min) min = sbuf[c];
-			if (sbuf[c] > 0.999) sbuf[c] = 0.999; else if (sbuf[c] < -0.999) sbuf[c] = -0.999;
+			if (sbuf[c] > max)
+				max = sbuf[c];
+
```
Comment (pulkomandy) [inline Source/stAiffWindow.cpp]: I would prefer no blank line here, these 3 operations are closely related

File: Source/stAiffWindow.cpp (hunk 1 above)
Comment (alwayslivid) [reply Source/stAiffWindow.cpp]: Will do, although this commit was primarily focusing on the fact that the program could not be compiled, rather than the code style.

I will follow up with another pull request afterwards.
